# Generated by Django 5.1 on 2025-11-03 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('facility', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='observations/before/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('rectification_details', models.TextField(blank=True)),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='observations/after/')),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
