# Generated by Django 5.1 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='verification_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
